### ISSUE TITLE
Scripts are hard-coded to system versions of tools

### ISSUE THREAD

**Issue by tseemann** [kissake/kSNP4#4] opened 2024-07-29 23:48 UTC
To make this code respect the user's environment,

For example, all `.pl` scripts should change
`#!/usr/bin/perl` to `#!/usr/bin/env perl`

The same for `bash` and `python`.

This will allow conda to work as intended.

**Comment by kissake** [comment] 2024-07-30 00:49
It sounds like you are having trouble making this code work under an Anaconda environment.  Can you share more details as to the system configuration that results in problems for you (Ideally enough information to reproduce the issue)?  Example details might include:
 - OS and version (e.g. RHEL 9.4)
 - Anaconda version
 - How you installed or otherwise accessed kSNP on the system.

I generally take your meaning and have interest in making this tool more generally available (e.g. by taking advantage of the cross-platform nature of the underlying tools), but it is very helpful to have a specific test case that fails when making changes.

**Comment by tseemann** [comment] 2024-07-30 02:04
This is independent of Anaconda.

This is about best practices for Unix scripts.
Your code is _forcing_ me to use `/usr/bin/*` tools, whereas the `env` method I explain will ensure it uses the perl/bash/python command thbe is FIRST IN MY PATH.

Often /usr/bin is an old out-dated version of the tool. In HPC and COnda and other systems those are not used. You should respect the user's wishes.

**Comment by kissake** [comment] 2024-07-30 02:24
For the targeted platforms, the /usr/bin instance of the given tool is the version of the tool that this implementation of kSNP is intended to work with, and it generally speaking gets vendor-supplied patches and updates.

Which is not to deny the benefits of your proposed changes; just to put the decision in context.  The goal in that design decision was to minimize chances of breakage and amount of required testing.

If you have a context you hope to use this tool in where this decision causes the tool to fail to operate correctly, that would be information that might successfully drive a change to this published code-base (if it seems to make sense to support that context).

Otherwise, given that this is open source and you sound passionate about this change, I encourage you to fork and make the proposed change for your own purposes if that is exciting for you.  I can even offer a sed script that should make the change for you without requiring much effort on your part:

```
# Do an in-place edit of all files where if the first line starts with #!/usr/bin/, 
# replace that text with "#!/usr/bin/env ".
# For any edited file, keep a backup in filename.backup.
sed --in-place=.backup -e '1 s/^#!\/usr\/bin\/\(.*)$/#!\/usr\/bin\/env \1/' *
```

I hope that is helpful information.

**Comment by kissake** [comment] 2024-08-04 22:04
Without more information on reproducing the problem you are concerned about, I'm going to close this ticket.  Happy to continue the conversation.

**Closed as not planned** 2024-08-04 22:05 UTC
